# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-20 16:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('date_of_birth', models.DateField(verbose_name='出生年月')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=7, verbose_name='性别')),
                ('education', models.CharField(choices=[('高中', '高中'), ('中专', '中专'), ('大专', '大专'), ('本科', '本科'), ('硕士', '硕士'), ('博士', '博士')], max_length=5, verbose_name='学历')),
                ('nation', models.CharField(max_length=10, verbose_name='民族')),
                ('politics', models.CharField(max_length=10, verbose_name='政治面貌')),
                ('mobile', models.CharField(max_length=11, verbose_name='联系电话')),
                ('office_phone', models.CharField(max_length=10, verbose_name='办公电话')),
                ('wechat', models.CharField(max_length=30, verbose_name='微信号')),
                ('address', models.CharField(default='', max_length=50, verbose_name='通信地址')),
                ('workplace', models.CharField(max_length=30, verbose_name='所在单位')),
                ('duty', models.CharField(blank=True, max_length=20, null=True, verbose_name='职务')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='职称')),
                ('profession_field', models.TextField(max_length=200, verbose_name='专业领域')),
                ('resume', models.TextField(blank=True, max_length=500, null=True, verbose_name='曾获得荣誉')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '会员申请信息',
            },
        ),
    ]
