# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-21 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='date_of_birth',
            field=models.CharField(max_length=20, verbose_name='出生年月'),
        ),
    ]
