# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-29 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingApp',
            fields=[
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名')),
                ('workplace', models.CharField(blank=True, max_length=30, null=True, verbose_name='所属单位')),
                ('mobile', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='联系电话')),
                ('email', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='邮箱地址')),
                ('demand', models.TextField(blank=True, max_length=500, null=True, verbose_name='食宿要求')),
                ('title', models.CharField(blank=True, max_length=25, null=True, verbose_name='报告题目')),
                ('abstract', models.TextField(blank=True, max_length=400, null=True, verbose_name='报告摘要')),
                ('sign', models.CharField(choices=[('1', '已签到'), ('0', '未签到')], default='0', max_length=5, null=True, verbose_name='签到状态')),
            ],
            options={
                'verbose_name_plural': '参会名单',
                'managed': True,
            },
        ),
    ]
