# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-29 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200529_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingapp',
            name='sign',
            field=models.CharField(choices=[('1', '已签到'), ('0', '未签到')], default='0', max_length=5, verbose_name='签到状态'),
        ),
    ]
